package cli

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders docs/cli.md from the same declarations the CLI runs on.
// `make spec` writes it; a test fails if the committed file differs.
func Markdown() (string, error) {
	cs, err := Commands()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }
	w("<!-- Generated by `make spec` from internal/contract/openapi.json and internal/cli. Do not edit. -->\n\n")
	w("# Townsquare command line\n\n")
	w("`townsquare` runs Townsquare (`serve`) and talks to it. Remote commands call a Townsquare server's `/api/v1` with an API key; local commands use this computer's data folder. Every remote command is generated from the API contract, so the CLI, the API and this page always match.\n\n")
	w("- First steps: `townsquare auth local` (on the Townsquare computer) or `townsquare auth login --url URL --profile NAME < keyfile`, then `townsquare doctor`.\n")
	w("- Machine-readable: `townsquare schema` ([CLI Spec](https://clispec.dev) v0.3), `townsquare <command> --request-schema` / `--response-schema`.\n")
	w("- Agent guide: `townsquare skills show` ([skills/townsquare/SKILL.md](../skills/townsquare/SKILL.md)).\n")
	w("- Settings precedence: flag > environment (`TOWNSQUARE_URL`, `TOWNSQUARE_API_KEY`, `TOWNSQUARE_PROFILE`, `TOWNSQUARE_OUTPUT`) > profile > default (this computer's server).\n\n")
	w("## Output\n\n")
	w("`-o auto` (default) prints text on a terminal and JSON when piped. Lists are `{\"items\": [...], \"total\": N, \"truncated\": bool}` (paged lists add `offset`, `limit`, `next_offset`); single records are printed as they are. Data goes to stdout; notes and errors go to stderr. With JSON output, an error is one JSON line on stderr: `{\"error\": {\"kind\", \"message\", \"hint\", \"retryable\", \"exit_code\", \"details\"}}`.\n\n")
	w("## Global flags\n\n| Flag | Type | What it does |\n|---|---|---|\n")
	for _, g := range Globals {
		n := "`" + g.Name + "`"
		if g.Short != "" {
			n = "`" + g.Short + "`, " + n
		}
		t := g.Type
		if len(g.Enum) > 0 {
			t = strings.Join(g.Enum, " \\| ")
		}
		w("| %s | %s | %s |\n", n, t, g.Desc)
	}
	w("| `--json` | boolean | Alias of `-o json` |\n| `--data` | path | Local commands: the data folder (default `~/.townsquare`) |\n\n")
	w("## Exit codes\n\n| Code | Kind | Retry? | Meaning |\n|---|---|---|---|\n")
	for _, k := range Kinds {
		w("| %d | `%s` | %s | %s |\n", k.ExitCode, k.Kind, yesNo(k.Retryable), k.Description)
	}
	for _, o := range Outcomes {
		w("| %d | `%s` (outcome) | n/a | %s |\n", o.Code, o.Name, o.Description)
	}
	w("\n## Remote commands\n\nEffects: `read_only` changes nothing; `idempotent` is safe to repeat; `non_idempotent` creates or sends something, so pass `--idempotency-key` to retry safely. Commands marked **needs --yes** refuse without a terminal unless `--yes` is given; preview them with `--dry-run`.\n")
	groups := map[string][]*Command{}
	var gnames []string
	for _, c := range cs {
		g := c.Words[0]
		if _, ok := groups[g]; !ok {
			gnames = append(gnames, g)
		}
		groups[g] = append(groups[g], c)
	}
	sort.Strings(gnames)
	for _, g := range gnames {
		w("\n### %s\n\n%s.\n", g, groupDesc[g])
		for _, c := range groups[g] {
			usage := "townsquare " + c.Name
			if c.Positional != nil {
				usage += " " + strings.ToUpper(c.Positional.Name)
			}
			w("\n#### `%s`\n\n%s. `%s /api/v1%s` · %s", usage, strings.TrimSuffix(c.Summary, "."), c.Method, c.Path, c.Effects)
			if c.Confirm {
				w(" · **needs --yes**")
			}
			if c.Cardinality == "unbounded" {
				w(" · paged")
			}
			if c.OutputKind == "opaque" {
				w(" · writes %s (`--deliver`)", c.MediaType)
			}
			w("\n")
			var ps []Param
			for _, p := range append(append([]Param{}, c.Query...), c.Body...) {
				if p.Name != "limit" && p.Name != "offset" {
					ps = append(ps, p)
				}
			}
			if len(ps) > 0 {
				w("\n")
				for _, p := range ps {
					t := p.Type
					if t == "array" {
						t = p.Items + " list"
					}
					extra := ""
					if p.Required {
						extra += " (required)"
					}
					if len(p.Enum) > 0 {
						extra += " One of: " + strings.Join(p.Enum, ", ") + "."
					}
					if p.Secret {
						extra += " Secret: pass `@file` or `@-`."
					}
					w("- `%s` %s%s %s\n", p.Flag, t, extra, strings.TrimSpace(p.Desc))
				}
			}
			w("\n```sh\n%s\n```\n", strings.Join(c.Examples, "\n"))
		}
	}
	w("\n## Setup and inspection\n\n")
	for _, s := range builtinSpecs {
		w("- `townsquare %s`: %s (%s)\n", s.Name, s.Summary, s.Effects)
	}
	w("\n## Local commands\n\nThese use this computer's data folder (`--data`) and need no server or key.\n\n")
	var ln []string
	for n := range localSpecs {
		ln = append(ln, n)
	}
	sort.Strings(ln)
	for _, n := range ln {
		s := localSpecs[n]
		w("- `townsquare %s`: %s Example: `%s`\n", n, s.Summary, s.Examples[0])
	}
	return b.String(), nil
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}
