// Package contract holds the single source of truth for Townsquare's interfaces:
// openapi.json, generated by tools/gen_openapi.py (edit that, then `make spec`).
// The REST API is tested against it (routes and response shapes), and the
// `townsquare` CLI builds every remote command, its help, its `schema` output
// and docs/cli.md from it (the x-cli entries). Don't edit openapi.json by hand.
package contract

import _ "embed"

//go:embed openapi.json
var openAPI []byte

// OpenAPI returns the API contract (OpenAPI 3.1 JSON).
func OpenAPI() []byte { return openAPI }
